/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Hangul {
  constructor(text: string)
  disassemble(): string
  getChoseong(): string
  hasBatchim(): boolean
  josa(pair: string): string
}

export declare function assemble(text: string): string
