/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Hangul {
  constructor(text: string)
  disassemble(): string
  getChoseong(): string
  hasBatchim(): boolean
  josa(pair: string): string
}

export type AssemblePolicy = "next-syllable" | "compound-final"

export declare function assemble(text: string, policy?: AssemblePolicy): string
